language: c
os:
  - osx

# XXX Doesn't work on OS X VM's currently (Nov 2015).
cache:
  directories:
  - $HOME/.stack

env:
  - PATH=$HOME/.local/bin:$PATH

before_install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin

install:
  - brew update
  - brew tap homebrew/science
  - brew install r zeromq python
  - pip install ipython
  - stack setup
  - stack --no-terminal -j2 build --only-snapshot --prefetch --test --bench

script:
  # XXX no tests for now since it times out.
  - stack --no-terminal -j2 build --pedantic
