language: c
os:
  - osx

# XXX Doesn't work on OS X VM's currently (Nov 2015).
cache:
  directories:
  - $HOME/.stack

env:
  - PATH=$HOME/.local/bin:$PATH

# XXX see https://github.com/travis-ci/travis-ci/issues/4709
before_install:
  - sudo security delete-certificate -Z 2F173F7DE99667AFA57AF80AA2D1B12FAC830338 /System/Library/Keychains/SystemRootCertificates.keychain
  - rvm osx-ssl-certs update all

install:
  - curl -LO https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-$TRAVIS_OS_NAME-x86_64.tar.gz
  - tar xf stack-0.1.6.0-$TRAVIS_OS_NAME-x86_64.tar.gz
  - mkdir -p ~/.local/bin
  - cp stack-0.1.6.0-$TRAVIS_OS_NAME-x86_64/stack ~/.local/bin
  - brew install zeromq && brew update && brew tap homebrew/science && brew install r
  - stack setup
  - stack --no-terminal -j1 build --only-snapshot --prefetch --test --bench

script:
  # XXX no tests for now since it times out.
  - stack --no-terminal -j1 build --pedantic
