version: "{build}"
os: Windows Server 2012 R2
platform: x86
cache: C:\Users\appveyor\AppData\Roaming\stack

build:
  verbosity: normal

deploy: off

init:
  ps: |
    Get-Date
    $ErrorActionPreference = "Stop"

install:
  ps: |
    Write-Host "Adding GnuWin32 tools to PATH"
    $env:PATH = "C:\Program Files (x86)\Git\bin;" + $env:PATH
    
    Write-Host "Downloading R.vhd"
    bash -c 'curl -s -L https://rportable.blob.core.windows.net/r-portable/master/R.vhd.gz | gunzip -c > ../R.vhd'
    bash -c 'curl -sOL https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-i386-windows.zip'
    7z e stack-0.1.2.0-i386-windows.zip
    mkdir 'C:\stack'
    mv stack-0.1.2.0-i386-windows.exe C:\stack\stack.exe

    Write-Host "Getting full path for R.vhd"
    $ImageFullPath = Get-ChildItem "..\R.vhd" | % { $_.FullName }
    $ImageSize = (Get-Item $ImageFullPath).length
    echo "$ImageFullPath [$ImageSize bytes]"
    
    Write-Host "Mounting R.vhd"
    $RDrive = [string](Mount-DiskImage -ImagePath $ImageFullPath -Passthru | Get-DiskImage | Get-Disk | Get-Partition | Get-Volume).DriveLetter + ":"
    # Assert that R was mounted properly
    if ( -not (Test-Path "${RDrive}\R\bin" -PathType Container) ) {
      Throw "Failed to mount R. Could not find directory: ${RDrive}\R\bin"
    }
    echo "R is now available on drive $RDrive"

    Write-Host "Setting PATH"
    $env:PATH = $RDrive + '\Rtools\bin;' + $RDrive + '\Rtools\MinGW\bin;' + $RDrive + '\Rtools\gcc-4.6.3\bin;' + $RDrive + '\R\bin\i386;' + 'C:\stack;' + $env:PATH
    $env:PATH.Split(";")
    
    Write-Host "Setting R_LIBS_USER"
    $env:R_LIBS_USER = 'c:\RLibrary'
    mkdir $env:R_LIBS_USER

    Write-Host "Launching stack"
    stack setup --verbose --no-terminal
    stack test --only-snapshot --prefetch --no-terminal
    stack bench --only-snapshot --prefetch --no-terminal
    stack haddock --only-snapshot --prefetch --no-terminal

build_script:
  - stack build --haddock --pedantic --no-terminal

test_script:
  - stack test --pedantic --no-terminal
  - stack bench --pedantic --no-terminal
