packages:
- examples
- H
- IHaskell
- inline-r
resolver: lts-3.13

docker:
  # Disabled by default. Use --docker on command line to enable.
  enable: false
  repo: tweag/haskellr:latest

nix-shell:
    enable: false
    packages: [ python34Packages.ipython, R, zeromq, pkgconfig, zlib, ghc ]
