packages:
- examples
- H
- IHaskell
- inline-r
resolver: lts-3.13
extra-deps:
- tasty-0.11.0.2
- tasty-expected-failure-0.11.0.3

docker:
  # Disabled by default. Use --docker on command line to enable.
  enable: false
  repo: tweag/haskellr:latest

nix:
    enable: false
    packages: [ python34Packages.ipython, R, zeromq, pkgconfig, zlib ]
    ## Right now, using just packages: is OK on Linux, not OSX
    #shell-file: ./shell.nix
